### ISSUE TITLE
Check v2 signature protocol in terms of change in NeoFS API

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-rest-gw#78]
We have added wallet connect signature type in native protocol, see https://github.com/nspcc-dev/neofs-api/pull/206

It seems like signature format has changed in wallet connect v2.0. For now we can still use v1.0 signatures, but it may be changed in the future. Consider adopting it in API (see if https://github.com/CityOfZion/wallet-connect-sdk/tree/develop is affected).

Also let's check what NEO wallets support v2.0 signatures (look for CHANGELOGs or maybe even code).
- Neon wallet
- Aero
- O3 wallet
- Onto ?

**Comment by mike-petrov** [comment]
I have looked through all the repositories of these wallets (Neon wallet, Aero, O3 wallet, Onto), looked into the code, CHANGELOGs, but there is no explicit indication of the migration to a new signature.

As for [walletConnect v2 documentation page](https://docs.walletconnect.com/2.0), we have this message:
> This is unreleased documentation for WalletConnect Docs v2.0-rc version.
For up-to-date documentation, see the [latest version](https://docs.walletconnect.com/) (v1.0).

Also on [Migrating from v1.x page](https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0) we have message:
> WalletConnect v2.0 is NOT backwards-compatible with v1.0. Therefore we must coordinate a migration schedule to ensure end-users do not suffer from this transition.
>Most importantly we must migrate Wallets before Dapps can start supporting v2.0. This is because Wallets can support both versions in parallel and route connection requests to corresponding clients using the version number specified in the URI present in the QR Code or Deep Link.
>Once we reach a significant quota of Wallets supporting v2.0 then we can start migrating Dapps as they will be able to simply upgrade the major version of their packages on NPM.

It seems that's why wallets are in no hurry to use the new version of the signature.

**Comment by alexvanin** [comment]
Let's see how v2 signature looks like.

**Comment by KirillovDenis** [comment]
It seems we need somehow change [rfc6979](https://github.com/nspcc-dev/rfc6979/blob/24b8ce9606a00167b4f4efcf56ff1c02f8cd0d37/ecdsa.go#L17) to be able use `salt` as `k` number.
Because of https://github.com/CityOfZion/neon-js/blob/f316675898117cddf03ea089e3177ef05877845f/packages/neon-core/src/wallet/signing.ts#L23

See more links in draft PR #84

**Comment by KirillovDenis** [comment]
> Also let's check what NEO wallets support v2.0 signatures

https://explorer.walletconnect.com/?version=2&page=2
